### ISSUE TITLE
Sending request body inside GET requests causes issues when using with reverse proxy

### ISSUE THREAD

**Issue by nikitavbv** [Finnerale/mlflow-rs#3]
Hi! First of all, thank you for working on this crate.

I have noticed that getting an experiment by name fails with a 400 error for me. In other words, I am doing something as simple as:
```
client.get_experiment_by_name(experiment_name)
```

And getting a response which looks like this:
```
Err(Storage(Unknown 400 error:
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 400 (Bad Request)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>400.</b> <ins>That’s an error.</ins>
  <p>Your client has issued a malformed or illegal request.  <ins>That’s all we know.</ins>
))
```

After a quick troubleshooting session, I figured out that I don't get this error with MLflow instance running locally, but I do get the error above when working with MLflow instance deployed to [Google Cloud Run](https://cloud.google.com/run).

That is quite easy to explain: Google Cloud Run uses a reverse proxy, which forwards all the requests to the actual container. And if I understood correctly [from the way GetExperimentByName is implemented](https://github.com/Finnerale/mlflow-rs/blob/master/src/backend/rest.rs#L478), this crate sends a message body inside the request body. While that is something that is not prohibited by HTTP spec, some proxy implementations reject some requests (as Google Frontend proxy does in my case) and it is usually advised to avoid sending request body when using GET ([see here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET)).

I tried hacking execute method a bit to use query params and seems that it works fine that way.

The proposed fix for this is to switch to query params for all GET requests. What do you think?

**Comment by luleyleo** [comment]
Huh, interesting, never though about this.
It seems like a good idea to pass the parameters as query params then :+1:

**Comment by nikitavbv** [comment]
@Finnerale Please see this merge request which switches to query params for get requests: https://github.com/Finnerale/mlflow-rs/pull/4

**Comment by nikitavbv** [comment]
Thank you for reviewing and merging this.
